# Generated by Django 4.0.3 on 2022-03-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrelations',
            old_name='is_bookmarks',
            new_name='in_bookmarks',
        ),
    ]
